config/routes.rb
MusicApp::Application.routes.draw do
  resources :users do
    collection do
      get 'activate'
    end
  end

  resource :session

  resources :bands do
    resources :albums, :only => [:index, :new, :create, :edit]
  end

  resources :albums do
    resources :tracks, :only => [:index, :new, :create, :edit]
  end

  resources :tracks do
    resources :notes, :only => [:index, :new, :create, :edit]
  end

  resources :notes, :only => :destroy

end

app/models/album.rb
class Album < ActiveRecord::Base
  attr_accessible :band_id, :album_type, :name
  validates :band_id, :album_type, :name, presence: true

  belongs_to(
    :band,
    class_name: "Band",
    foreign_key: :band_id,
    primary_key: :id,
  )

  has_many(
    :tracks,
    class_name: "Track",
    foreign_key: :album_id,
    primary_key: :id,
    dependent: :destroy
  )
end

app/models/band.rb
class Band < ActiveRecord::Base
  attr_accessible :name
  validates :name, presence: true

  has_many(
    :albums,
    class_name: "Album",
    foreign_key: :band_id,
    primary_key: :id,
    dependent: :destroy
  )
end

app/models/note.rb
class Note < ActiveRecord::Base
  attr_accessible :text, :track_id, :user_id

  validates :text, :track_id, :user_id, presence: true

  belongs_to(
    :user,
    class_name: "User",
    foreign_key: :user_id,
    primary_key: :id
  )

  belongs_to(
    :track,
    class_name: "Track",
    foreign_key: :track_id,
    primary_key: :id
  )

end

app/models/track.rb
class Track < ActiveRecord::Base
  attr_accessible :album_id, :track_type, :lyrics, :name
  validates :album_id, :track_type, :lyrics, :name, presence: true

  belongs_to(
    :album,
    class_name: "Album",
    foreign_key: :album_id,
    primary_key: :id
  )

  has_many(
    :notes,
    class_name: "Note",
    foreign_key: :track_id,
    primary_key: :id
  )

end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base
  attr_accessible :email, :password_digest, :session_token, :password, :activation_token, :activated

  validates :email, :password_digest, :session_token, :activation_token, presence: true
  validates_inclusion_of :activated, :in => [true, false]
  validates :email, uniqueness: true

  before_validation :set_session_token
  before_validation :set_activation_token
  before_validation :set_activated

  has_many(
    :notes,
    class_name: "Note",
    foreign_key: :user_id,
    primary_key: :id
  )

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
  end

  def password=(secret)
    self.password_digest = BCrypt::Password.create(secret)
  end

  def is_password?(secret)
    BCrypt::Password.new(self.password_digest).is_password?(secret)
  end

  def self.find_by_credentials(email, secret)
    user = User.find_by_email(email)
    user.is_password?(secret) ? user : nil
  end

  private

  def set_session_token
    self.session_token ||= User.generate_session_token
  end

  def set_activation_token
    self.activation_token ||= User.generate_session_token
  end

  def set_activated
    self.activated ||= false
    true
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def index
    @albums = Album.all
    render :index
  end

  def show
    @album = Album.find(params[:id])
    render :show
  end

  def new
    @album = Album.new
    @bands = Band.all
    render :new
  end

  def create
    @album = Album.new(params[:album])
    if @album.save
      redirect_to @album
    else
      flash[:notice] ||= []
      flash[:notice] << "Your album was not created."
      redirect_to new_album_url
    end
  end

  def edit
    @album = Album.find(params[:id])
    @bands = Band.all
    render :edit
  end

  def update
    @album = Album.find(paras[:id])
    @album.update_attributes(params[:album])

    redirect_to @album
  end

  def destroy
    Album.find(params[:id]).destroy

    redirect_to albums_url
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def index
    @bands = Band.all
  end

  def show
    @band = Band.find(params[:id])
  end

  def new
    @band = Band.new
  end

  def create
    @band = Band.new(params[:band])
    if @band.save
      redirect_to @band
    else
      flash[:notice] ||= []
      flash[:notice] << "Your band was not created."
      redirect_to new_band_url
    end
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def update
    @band = Band.find(params[:id])
    @band.update_attributes(params[:band])
    redirect_to @band
  end

  def destroy
    Band.find(params[:id]).destroy
    redirect_to bands_url
  end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  def new
    @note = Note.new
  end

  def create
    params[:note][:track_id] = params[:track_id]
    params[:note][:user_id] = current_user.id
    @note = Note.create(params[:note])
    if @note.save
      redirect_to @note.track
    else
      flash[:notice] ||= []
      flash[:notice] << "Your note was not created."
      redirect_to @note.track
    end
  end

  def destroy
    note = Note.find(params[:id])
    track = note.track
    Note.find(params[:id]).destroy
    redirect_to track
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_credentials(params[:user][:email],params[:user][:password])
    if log_in_user!.nil?
      flash[:notice] ||= []
      flash[:notice] << "Cannot log in"
      redirect_to new_session_url
    else
      redirect_to current_user
    end
  end

  def destroy
    session[:session_token] = nil
    redirect_to new_session_url
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  def index
    @tracks = Track.find_all_by_album_id(params[:album_id])

    render @tracks
  end

  def show
    @track = Track.find(params[:id])
    @notes = @track.notes
    @note = Note.new

    render :show
  end

  def new
    @track = Track.new
    @albums = Album.all
    render :new
  end

  def create
    @track = Track.new(params[:track])
    if @track.save
      redirect_to track_url(@track.id)
    else
      flash[:notice] ||= []
      flash[:notice] << "Your track was not created."
      redirect_to new_album_track_url
    end
  end

  def edit
    @track = Track.find(params[:id])

    render :edit
  end

  def update
    @track = Track.find(params[:id])
    @track.update_attributes(params[:track])

    redirect_to @track
  end

  def destroy
    @track = Track.find(params[:id])
    @album = @track.album
    @track.destroy

    redirect_to album_url(@album)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      session[:session_token] = @user.session_token
      msg = UserMailer.welcome_email(@user)
      msg.deliver!
      if log_in_user!.nil?
        redirect_to new_session_url
        flash[:notice] ||= []
        flash[:notice] << "Please activate via email first."
      else
        redirect_to @user
      end
    else
      flash[:notice] ||= []
      flash[:notice] << "Could not sign up"
    end
  end

  def show
    @user = User.find_by_id(params[:id])
  end

  def activate
    user = User.find_by_activation_token(params[:activation_token])
    user.activated = true
    user.save
    redirect_to bands_url
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user = User.find_by_session_token(session[:session_token])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_in_user!
    session[:session_token] = @user.session_token if @user.activated
  end

end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/edit.html.erb
<form action="<%= albums_url %>" method="POST">
  <input type="hidden" name="_method" value="PUT">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label for="album_name">Album Name:</label>
  <input type="text" id="album_name" name="album[name]" value="<%= @album.name %>">
  <br>
  <label for="album_band_id">Band Name:</label>
  <select name="album[band_id]" id="album_band_id">
    <%= @bands.each do |band| %>
      <% selected = band == @album.band ? "selected" : "" %>
      <option value="<%= band.id %>" <%= selected.html_safe %>><%= band.name %></option>
    <% end %>
  </select>
  <br>
  <label for="album_album_type">Live or Studio?:</label>
  <select name="album[album_type]" id="album_album_type">
    <option value="Live">Live</option>
    <option value="Studio">Studio</option>
  </select>
  <br>
  <input type="submit" value="Create Album">
</form>

app/views/albums/index.html.erb
<ul>
  <% @albums.each do |album| %>
    <li>
      <%= link_to album.name, album_url(album.id) %>
    </li>
  <% end %>
</ul>

app/views/albums/new.html.erb
<form action="<%= band_albums_url(params[:band_id]) %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label for="album_name">Album Name:</label>
  <input type="text" id="album_name" name="album[name]" value="<%= @album.name %>">
  <br>
  <label for="album_band_id">Band Name:</label>
  <select name="album[band_id]" id="album_band_id">
    <%= @bands.each do |band| %>
    <% selected = band == Band.find(params[:band_id]) ? "selected" : "" %>
      <option value="<%= band.id %>" <%= selected.html_safe %>><%= band.name %></option>
    <% end %>
  </select>
  <br>
  <label for="album_album_type">Live or Studio?:</label>
  <select name="album[album_type]" id="album_album_type">
    <option value="Live">Live</option>
    <option value="Studio">Studio</option>
  </select>
  <br>
  <input type="submit" value="Create Album">
</form>

app/views/albums/show.html.erb
<h1><%= @album.name %> by <%= link_to @album.band.name, band_url(@album.band_id) %></h1>
<h2>Type: <%= @album.album_type %></h2>
<h3>Tracks</h3>
<ol>
<% @album.tracks.each do |track| %>
  <li>
    <%= link_to track.name, track_url(track.id) %>
  </li>
<% end %>
</ol>
<%= button_to "Delete Album", album_url(@album), method: :delete %>

app/views/bands/edit.html.erb
<form action="<%= band_url(@band.id) %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="PUT">
  <label for="band_name">Band Name:</label>
  <input type="text" name="band[name]" value="<%= @band.name %>">
  <br>
  <input type="submit" value="Update Band">
</form>

app/views/bands/index.html.erb
<% @bands.each do |band| %>
  <%= link_to band.name, band_url(band) %>
  <br>
<% end %>

app/views/bands/new.html.erb
<form action="/bands" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label for="band_name">Band Name:</label>
  <input type="text" id="band_name" name="band[name]">
  <br>
  <input type="submit" value="Create Band">
</form>

app/views/bands/show.html.erb
<h1><%= @band.name %></h1>
<h2>Albums</h2>
<ul>
  <% @band.albums.each do |album| %>
    <li>
      <%= link_to album.name, album_url(album.id) %>
      <br>
      <ol>
        <% album.tracks.each do |track| %>
          <li>
            <%= link_to track.name, track_url(track.id) %>
          </li>
        <% end %>
      </ol>
    </li>
  <% end %>
</ul>
<%= button_to "Delete Band", band_url(@band), method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if logged_in? %>
  <%= current_user.email %>
  <%= button_to "Log Out", session_url, method: :delete %>
<% end %>
<%= yield %>

</body>
</html>

app/views/notes/_note.html.erb
<br>
"<%= note.text %>"
<br>
by <strong><%= note.user.email %></strong>.  <em>Posted <%= time_ago_in_words(note.created_at) %> ago.</em>
<br>
<%= button_to "Delete Note", note_url(note), method: :delete %>
<br>

app/views/tracks/new.html.erb
<form action="<%= album_tracks_url(params[:album_id]) %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label for="track_name">Name:</label>
  <input type="text" id="track_name" name="track[name]">
  <br>
  <label for="track_album_id">Album:</label>
  <select name="track[album_id]" id="track_album_id">
    <% @albums.each do |album| %>
      <% selected = album == Album.find(params[:album_id]) ? "selected" : "" %>
      <option value="<%= album.id %>" <%= selected.html_safe %>><%= album.name %></option>
    <% end %>
  </select>
  <br>
  <label for="track_track_type">Bonus or Regular?:</label>
  <select id="track_track_type" name="track[track_type]">
    <option value="Bonus">Bonus</option>
    <option value="Regular">Regular</option>
  </select>
  <br>
  <label for="track_lyrics">Lyrics:</label>
  <br>
  <input type="text" id="track_lyrics" name="track[lyrics]">
  <br>
  <input type="submit" value="Add Track">
</form>

app/views/tracks/show.html.erb
<h1><%= @track.name %></h1>
<h2>Album: <%= link_to @track.album.name, album_url(@track.album_id) %></h2>
<h2>Band: <%= link_to @track.album.band.name, band_url(@track.album.band_id) %></h2>
<h3>Lyrics:</h3>
<%= @track.lyrics %>
<h3>Notes:</h3>
<form action="<%= track_notes_url(params[:id]) %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label for="note_text">Note:</label>
  <br>
  <input type="text" id="note_text" name="note[text]">
  <br>
  <input type="submit" value="Add Note">
</form>
<br>
<%= render partial: "notes/note", collection: @notes.reverse %>
<%= button_to "Delete Track", track_url(@track), method: :delete %>

app/views/users/new.html.erb
<form action="<%= users_url %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label for="user_email">User Email</label>
  <input type="text" name="user[email]" id="user_email">
  <br>
  <label for="user_password">Password</label>
  <input type="text" name="user[password]" id="user_password">
  <br>
  <input type="submit" value="Create Account">
</form>

app/views/users/show.html.erb
<%= @user.email %>'s page.